version: '3.3'
services:
    local-db:
         image: mysql:5.6.34
         restart: always
         container_name: local-mysql
         environment:
           MYSQL_DATABASE: 'test'
           MYSQL_ROOT_PASSWORD: ''
         ports:
           - '3306:3306'
         expose:
           - '3306'
         volumes:
            - ./mysql/data/:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
#           - ./mysql/init/:/docker-entrypoint-initdb.d/:rw


    local-redis:
        container_name: local-redis
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro

    local-nginx:
      image: nginx
      container_name: local-nginx
      ports:
        - "8003:8003"
      volumes:
        - ./nginx/config:/etc/nginx

    tomcat:
        restart: always
        image: local-image:1.0
        container_name: local-tomcat
        ports:
          - 8080:8080
        volumes:
          - ./tomcat/webapps:/opt/tomcat/webapps
          - ./tomcat/shared/classes:/opt/tomcat/shared/classes
          - ./tomcat/conf/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
          - ./tomcat/shell.sh:/root/shell.sh
        environment:
          - VPC_ENV=local
        depends_on:
          - local-redis
          - local-mysql
 #command: "chmod +x /root/shell.sh && /root/shell.sh && /opt/tomcat/bin/catalina.sh run && tail -f /opt/tomcat/logs/*"
        command: "/opt/tomcat/bin/catalina.sh run && tail -f /opt/tomcat/logs/*"
